import OpenAI from "openai";

// the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

interface CodeAnalysisResult {
  score: number;
  securityIssues: Record<string, any>[];
  performanceIssues: Record<string, any>[];
  maintainabilityIssues: Record<string, any>[];
  summary: string;
}

export async function analyzePRDiff(diff: string): Promise<CodeAnalysisResult> {
  const response = await openai.chat.completions.create({
    model: "gpt-4o",
    messages: [
      {
        role: "system",
        content: `You are an expert code reviewer. Analyze the provided code diff and return a JSON object with:
        - score: 0-100 based on overall quality
        - securityIssues: array of security concerns
        - performanceIssues: array of performance issues
        - maintainabilityIssues: array of maintainability concerns
        - summary: human readable summary of changes
        Each issue should have a title, description, and severity (low, medium, high)`
      },
      {
        role: "user",
        content: diff
      }
    ],
    response_format: { type: "json_object" }
  });

  const content = response.choices[0].message.content;
  if (!content) {
    throw new Error("No response from OpenAI");
  }

  return JSON.parse(content) as CodeAnalysisResult;
}

export function generatePRComment(analysis: CodeAnalysisResult): string {
  const issueToMd = (issues: Record<string, any>[], type: string) => {
    if (issues.length === 0) return '';
    return `
### ${type} Issues
${issues.map(i => `- **${i.title}** (${i.severity})
  ${i.description}`).join('\n')}
`;
  };

  return `# AI Code Review Summary

Overall Score: ${analysis.score}/100

${analysis.summary}

${issueToMd(analysis.securityIssues, 'Security')}
${issueToMd(analysis.performanceIssues, 'Performance')}
${issueToMd(analysis.maintainabilityIssues, 'Maintainability')}

---
*Generated by BaseSync AI Code Review*`;
}